"""add_processing_time_to_ocr

Revision ID: f531c9906164
Revises: 03706a28432e
Create Date: 2026-04-11 23:24:44.160799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f531c9906164'
down_revision: Union[str, Sequence[str], None] = '03706a28432e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('processing_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_results', 'processing_time')
    # ### end Alembic commands ###
